version: "3"
services:
  zyspotify:
    image: kaitallaoua/zyspotify

    # bind to a vpn container already running if desired
    # such as https://github.com/wfg/docker-openvpn-client
    # network_mode: container:openvpn-client
    volumes:
      - ./config:/root/config
      - ./Music:/root/Music
    environment:

      # These should be removed after the first run. since credentials cached in db
      - USERNAME=example@gmail.com
      - PASSWORD=hunter2